### ISSUE TITLE
REGRESSION : Segfault in mipmap with i965, ok with ES

### ISSUE THREAD

**Issue by zezinho42** [glmark2/glmark2#107]
I have a regression only in default mode. With glmark2-es2 it does not segfault.
The regression is against 20170210 checkout. 

Backtrace follows :

[New Thread 0x7ffff687a700 (LWP 19793)]
=======================================================
    glmark2 2017.07
=======================================================
    OpenGL Information
    GL_VENDOR:     Intel Open Source Technology Center
    GL_RENDERER:   Mesa DRI Intel(R) Ironlake Mobile 
    GL_VERSION:    2.1 Mesa 19.2.0
=======================================================

Thread 1 "glmark2" received signal SIGSEGV, Segmentation fault.
0x0000000000000000 in ?? ()
(gdb) backtrace 
#0  0x0000000000000000 in ?? ()
#1  0x00000000004a943e in setup_texture (mag_filter=<optimized out>, min_filter=<optimized out>, image=..., tex=0x51cb78) at ../src/texture.cpp:94
#2  Texture::load (textureName="crate-base", pTexture=pTexture@entry=0x51cb78) at ../src/texture.cpp:135
#3  0x000000000049f1e1 in SceneTexture::setup (this=0x51c9d0) at ../src/scene-texture.cpp:143
#4  0x0000000000422436 in Benchmark::setup_scene (this=0x8dca10) at ../src/benchmark.cpp:111
#5  0x0000000000425b75 in MainLoop::step (this=this@entry=0x8d4030) at ../src/main-loop.cpp:86
#6  0x0000000000417ce0 in do_benchmark (canvas=...) at ../src/main.cpp:123
#7  0x0000000000416178 in main (argc=<optimized out>, argv=<optimized out>) at ../src/main.cpp:221

**Comment by zezinho42** [comment]
I could rebuild the 20170210 code in my recent system, and it also segfaults. So the regression seems to be because of either new gcc or new libs...
