### ISSUE TITLE
terminate called after throwing an instance of st

### ISSUE THREAD

**Issue by 1640675651** [glmark2/glmark2#110]

**Comment by 1640675651** [comment]
I configured with x11-gl, but get a problem running the program.

terminate called after throwing an instance of 'std::logic_error'
what(): basic_string::_M_construct NULL is not valid

**Comment by afrantzis** [comment]
Could you please run with `gdb` and provide a backtrace? That will help us pinpoint the issue. Thanks!

**Comment by lucmann** [comment]
@1640675651 you may try `glmark2 --reuse-context`. It works for me anyway. my used renderer is 3.1 Mesa 20.2.0-devel llvmpipe.
Generally the below error is caused by trying to read the memory that you cannot access, for instance, a NULL pointer.
```
terminate called after throwing an instance of 'std::logic_error'
what(): basic_string::_M_construct NULL is not valid
```
in gdb, I've got that `glGetString(GL_VERSION)`  called secondly at MainLoop::step() returned a NULL. I don't know why. But this should be the problem.
```
Thread 1 "glmark2" hit Breakpoint 2, CanvasGeneric::reset (this=0x7fffffffe1f0) at ../src/canvas-generic.cpp:62
warning: Source file is more recent than executable.
62	    if (!supports_gl2()) {
#0  CanvasGeneric::reset (this=0x7fffffffe1f0) at ../src/canvas-generic.cpp:62
#1  CanvasGeneric::reset (this=0x7fffffffe1f0) at ../src/canvas-generic.cpp:49
#2  0x000055555556fd2b in main (argc=<optimized out>, argv=<optimized out>) at ../src/main.cpp:205
CanvasGeneric::supports_gl2 (this=0x7fffffffe1f0) at ../src/canvas-generic.cpp:196
196	{
197	    std::string gl_version_str(reinterpret_cast<const char*>(glGetString(GL_VERSION)));
std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string (__a=..., __s=<optimized out>, this=<optimized out>)
    at ../src/canvas-generic.cpp:197
197	    std::string gl_version_str(reinterpret_cast<const char*>(glGetString(GL_VERSION)));
std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_Alloc_hider::_Alloc_hider (__a=..., __dat=<optimized out>, this=<optimized out>)
    at /usr/include/c++/8/ext/new_allocator.h:79
79	      new_allocator() _GLIBCXX_USE_NOEXCEPT { }
glGetString () at src/mapi/glapi/gen/glapi_x86-64.S:9855
9855		call	_x86_64_get_dispatch@PLT
_x86_64_get_dispatch () at src/mapi/glapi/gen/glapi_x86-64.S:48
48		movq	_glapi_tls_Dispatch@GOTTPOFF(%rip), %rax
49		movq	%fs:(%rax), %rax
_x86_64_get_dispatch () at src/mapi/glapi/gen/glapi_x86-64.S:50
50		ret
glGetString () at src/mapi/glapi/gen/glapi_x86-64.S:9856
9856		movq	2200(%rax), %r11
9857		jmp	*%r11
_mesa_GetString (name=7938) at ../src/mesa/main/getstring.c:117
117	{
118	   GET_CURRENT_CONTEXT(ctx);
122	   if (!ctx)
179	   return ctx->Driver.CurrentExecPrimitive != PRIM_OUTSIDE_BEGIN_END;
127	   if (ctx->Const.VendorOverride && name == GL_VENDOR) {
132	   assert(ctx->Driver.GetString);
135	      const GLubyte *str = ctx->Driver.GetString(ctx, name);
st_get_string (ctx=0x7fffec0c2010, name=7938) at ../src/mesa/state_tracker/st_cb_strings.c:44
44	{
46	   struct pipe_screen *screen = st->pipe->screen;
48	   switch (name) {
_mesa_GetString (name=7938) at ../src/mesa/main/getstring.c:136
136	      if (str)
140	   switch (name) {
146	         return (const GLubyte *) ctx->VersionString;
CanvasGeneric::supports_gl2 (this=<optimized out>) at ../src/canvas-generic.cpp:197
warning: Source file is more recent than executable.
197	    std::string gl_version_str(reinterpret_cast<const char*>(glGetString(GL_VERSION)));
Continuing.

Thread 1 "glmark2" hit Breakpoint 1, CanvasGeneric::supports_gl2 (this=<optimized out>) at ../src/canvas-generic.cpp:200
200	    size_t point_pos(gl_version_str.find('.'));
Continuing.

Thread 1 "glmark2" hit Breakpoint 2, CanvasGeneric::reset (this=0x7fffffffe1f0) at ../src/canvas-generic.cpp:62
62	    if (!supports_gl2()) {
CanvasGeneric::supports_gl2 (this=0x7fffffffe1f0) at ../src/canvas-generic.cpp:196
196	{
197	    std::string gl_version_str(reinterpret_cast<const char*>(glGetString(GL_VERSION)));
std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string (__a=..., __s=<optimized out>, this=<optimized out>)
    at ../src/canvas-generic.cpp:197
197	    std::string gl_version_str(reinterpret_cast<const char*>(glGetString(GL_VERSION)));
std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_Alloc_hider::_Alloc_hider (__a=..., __dat=<optimized out>, this=<optimized out>)
    at /usr/include/c++/8/ext/new_allocator.h:79
79	      new_allocator() _GLIBCXX_USE_NOEXCEPT { }
glGetString () at src/mapi/glapi/gen/glapi_x86-64.S:9855
9855		call	_x86_64_get_dispatch@PLT
_x86_64_get_dispatch () at src/mapi/glapi/gen/glapi_x86-64.S:48
48		movq	_glapi_tls_Dispatch@GOTTPOFF(%rip), %rax
49		movq	%fs:(%rax), %rax
_x86_64_get_dispatch () at src/mapi/glapi/gen/glapi_x86-64.S:50
50		ret
glGetString () at src/mapi/glapi/gen/glapi_x86-64.S:9856
9856		movq	2200(%rax), %r11
9857		jmp	*%r11
NoOpGetString (name=7938) at src/mapi/glapi/gen/glapitemp.h:1768
1768	{
1770	   RETURN_DISPATCH(GetString, (name), (F, "glGetString(0x%x);\n", name));
nop (func=0x7ffff743d3ab "GetString") at ../src/mapi/glapi/glapi_nop.c:86
86	   if (nop_handler)
NoOpGetString (name=7938) at src/mapi/glapi/gen/glapitemp.h:1770
1770	   RETURN_DISPATCH(GetString, (name), (F, "glGetString(0x%x);\n", name));
CanvasGeneric::supports_gl2 (this=<optimized out>) at ../src/canvas-generic.cpp:197
197	    std::string gl_version_str(reinterpret_cast<const char*>(glGetString(GL_VERSION)));
#0  CanvasGeneric::supports_gl2 (this=<optimized out>) at ../src/canvas-generic.cpp:197
#1  0x0000555555573fd6 in CanvasGeneric::reset (this=0x7fffffffe1f0) at ../src/canvas-generic.cpp:62
#2  CanvasGeneric::reset (this=0x7fffffffe1f0) at ../src/canvas-generic.cpp:49
#3  0x0000555555580a49 in MainLoop::step (this=0x555555924650) at ../src/main-loop.cpp:117
#4  0x00005555555723f8 in do_benchmark (canvas=...) at ../src/main.cpp:123
#5  0x0000555555570107 in main (argc=<optimized out>, argv=<optimized out>) at ../src/main.cpp:221
Breakpoint 3 at 0x555555580989: file ../src/main-loop.cpp, line 84.
Starting program: /usr/local/bin/glmark2 
Thread 1 "glmark2" hit Breakpoint 2, CanvasGeneric::reset (this=0x7fffffffe1f0) at ../src/canvas-generic.cpp:62
62	    if (!supports_gl2()) {
Continuing.

Thread 1 "glmark2" hit Breakpoint 1, CanvasGeneric::supports_gl2 (this=<optimized out>) at ../src/canvas-generic.cpp:200
200	    size_t point_pos(gl_version_str.find('.'));
Continuing.

Thread 1 "glmark2" hit Breakpoint 3, MainLoop::step (this=0x555555924650) at ../src/main-loop.cpp:84
84	            if (!Options::reuse_context)
$1 = false

```
