### ISSUE TITLE
UnicodeDecodeError  error.

### ISSUE THREAD

**Issue by aprekates** [glmark2/glmark2#119]
Debian 10 . 
An executable is created but i cant fix that unicode error and o installatoin happens.

$  ./waf configure --with-flavors=x11-gl
Setting top to                           : Traceback (most recent call last):
  File "/home/chomwitt/Λήψεις/glmark2-master/waflib/Logs.py", line 85, in emit
    self.emit_override(record)
  File "/home/chomwitt/Λήψεις/glmark2-master/waflib/Logs.py", line 95, in emit_override
    msg=self.formatter.format(record)
  File "/home/chomwitt/Λήψεις/glmark2-master/waflib/Logs.py", line 135, in format
    return msg%rec.args
UnicodeDecodeError: 'ascii' codec can't decode byte 0xce in position 15: ordinal not in range(128)
Logged from file Logs.py, line 167
Setting out to                           : Traceback (most recent call last):
  File "/home/chomwitt/Λήψεις/glmark2-master/waflib/Logs.py", line 85, in emit
    self.emit_override(record)
  File "/home/chomwitt/Λήψεις/glmark2-master/waflib/Logs.py", line 95, in emit_override
    msg=self.formatter.format(record)
  File "/home/chomwitt/Λήψεις/glmark2-master/waflib/Logs.py", line 135, in format
    return msg%rec.args
UnicodeDecodeError: 'ascii' codec can't decode byte 0xce in position 15: ordinal not in range(128)
Logged from file Logs.py, line 167
Checking for 'gcc' (C compiler)          : /usr/bin/gcc 
Checking for 'g++' (C++ compiler)        : /usr/bin/g++ 
Checking for header stdlib.h             : yes 
Checking for header string.h             : yes 
Checking for header stdint.h             : yes 
Checking for header stdio.h              : yes 
Checking for header dlfcn.h              : yes 
Checking for header unistd.h             : yes 
Checking for header jpeglib.h            : yes 
Checking for header math.h               : yes 
Checking for header string.h             : yes 
Checking for library m                   : yes 
Checking for library jpeg                : yes 
Checking for function memset             : yes 
Checking for function sqrt               : yes 
Checking for program 'pkg-config'        : /usr/bin/pkg-config 
Checking for 'libpng12'                  : not found 
Checking for 'libpng15'                  : not found 
Checking for 'libpng16'                  : yes 
Checking for 'x11'                       : yes 
Checking for 'libdrm'                    : yes 
Checking for 'gbm'                       : yes 
Checking for 'libudev'                   : yes 
Checking for 'mirclient'                 : not found 
Checking for 'wayland-client'            : yes 
Checking for 'wayland-egl'               : yes 
Prefix                                   : /usr/local 
Data path                                : /usr/local/share/glmark2 
Including extras                         : No 
Building flavors                         : ['x11-gl'] 
'configure' finished successfully (0.646s)
chomwitt@enous:~/Λήψεις/glmark2-master$ ./waf
Traceback (most recent call last):
  File "/home/chomwitt/Λήψεις/glmark2-master/waflib/Logs.py", line 85, in emit
    self.emit_override(record)
  File "/home/chomwitt/Λήψεις/glmark2-master/waflib/Logs.py", line 95, in emit_override
    msg=self.formatter.format(record)
  File "/home/chomwitt/Λήψεις/glmark2-master/waflib/Logs.py", line 135, in format
    return msg%rec.args
UnicodeDecodeError: 'ascii' codec can't decode byte 0xce in position 15: ordinal not in range(128)
Logged from file Logs.py, line 167
[ 1/70] Compiling src/main.cpp
[ 2/70] Compiling src/canvas-generic.cpp
[ 3/70] Compiling src/native-state-x11.cpp
[ 4/70] Compiling src/gl-state-glx.cpp
[ 5/70] Compiling src/glad/src/glx.c
[ 6/70] Compiling src/glad/src/gl.c
[ 7/70] Compiling src/libmatrix/log.cc
[ 8/70] Compiling src/libmatrix/mat.cc
[ 9/70] Compiling src/libmatrix/program.cc
[10/70] Compiling src/libmatrix/shader-source.cc
[11/70] Compiling src/libmatrix/util.cc
[12/70] Compiling src/benchmark-collection.cpp
[13/70] Compiling src/benchmark.cpp
[14/70] Compiling src/gl-headers.cpp
[15/70] Compiling src/gl-visual-config.cpp
[16/70] Compiling src/image-reader.cpp
[17/70] Compiling src/main-loop.cpp
[18/70] Compiling src/mesh.cpp
[19/70] Compiling src/model.cpp
[20/70] Compiling src/options.cpp
[21/70] Compiling src/scene-buffer.cpp
[22/70] Compiling src/scene-build.cpp
[23/70] Compiling src/scene-bump.cpp
[24/70] Compiling src/scene-clear.cpp
[25/70] Compiling src/scene-conditionals.cpp
[26/70] Compiling src/scene-default-options.cpp
[27/70] Compiling src/scene-desktop.cpp
[28/70] Compiling src/scene-effect-2d.cpp
[29/70] Compiling src/scene-function.cpp
[30/70] Compiling src/scene-grid.cpp
[31/70] Compiling src/scene-ideas/a.cc
[32/70] Compiling src/scene-ideas/d.cc
[33/70] Compiling src/scene-ideas/e.cc
[34/70] Compiling src/scene-ideas/i.cc
[35/70] Compiling src/scene-ideas/lamp.cc
[36/70] Compiling src/scene-ideas/logo.cc
[37/70] Compiling src/scene-ideas/m.cc
[38/70] Compiling src/scene-ideas/n.cc
[39/70] Compiling src/scene-ideas/o.cc
[40/70] Compiling src/scene-ideas/s.cc
[41/70] Compiling src/scene-ideas/splines.cc
[42/70] Compiling src/scene-ideas/t.cc
[43/70] Compiling src/scene-ideas/table.cc
[44/70] Compiling src/scene-ideas.cpp
[45/70] Compiling src/scene-jellyfish.cpp
[46/70] Compiling src/scene-loop.cpp
[47/70] Compiling src/scene-pulsar.cpp
[48/70] Compiling src/scene-refract.cpp
[49/70] Compiling src/scene-shading.cpp
[50/70] Compiling src/scene-shadow.cpp
[51/70] Compiling src/scene-terrain/base-renderer.cpp
[52/70] Compiling src/scene-terrain/blur-renderer.cpp
[53/70] Compiling src/scene-terrain/copy-renderer.cpp
[54/70] Compiling src/scene-terrain/luminance-renderer.cpp
[55/70] Compiling src/scene-terrain/normal-from-height-renderer.cpp
[56/70] Compiling src/scene-terrain/overlay-renderer.cpp
[57/70] Compiling src/scene-terrain/renderer-chain.cpp
[58/70] Compiling src/scene-terrain/simplex-noise-renderer.cpp
[59/70] Compiling src/scene-terrain/terrain-renderer.cpp
[60/70] Compiling src/scene-terrain/texture-renderer.cpp
[61/70] Compiling src/scene-terrain.cpp
[62/70] Compiling src/scene-texture.cpp
[63/70] Compiling src/scene.cpp
[64/70] Compiling src/shared-library.cpp
[65/70] Compiling src/text-renderer.cpp
[66/70] Compiling src/texture.cpp
[67/70] Compiling doc/glmark2.1.in
[68/70] Linking build/src/libmatrix-gl.a
[69/70] Linking build/src/libcommon-gl.a
[70/70] Linking build/src/glmark2
Traceback (most recent call last):
  File "/home/chomwitt/Λήψεις/glmark2-master/waflib/Logs.py", line 85, in emit
    self.emit_override(record)
  File "/home/chomwitt/Λήψεις/glmark2-master/waflib/Logs.py", line 95, in emit_override
    msg=self.formatter.format(record)
  File "/home/chomwitt/Λήψεις/glmark2-master/waflib/Logs.py", line 135, in format
    return msg%rec.args
UnicodeDecodeError: 'ascii' codec can't decode byte 0xce in position 15: ordinal not in range(128)
Logged from file Logs.py, line 167
'build' finished successfully (15.327s)
chomwitt@enous:~/Λήψεις/glmark2-master$ ./waf install --destdir=/home/chomwitt/bin
Traceback (most recent call last):
  File "/home/chomwitt/Λήψεις/glmark2-master/waflib/Logs.py", line 85, in emit
    self.emit_override(record)
  File "/home/chomwitt/Λήψεις/glmark2-master/waflib/Logs.py", line 95, in emit_override
    msg=self.formatter.format(record)
  File "/home/chomwitt/Λήψεις/glmark2-master/waflib/Logs.py", line 135, in format
    return msg%rec.args
UnicodeDecodeError: 'ascii' codec can't decode byte 0xce in position 15: ordinal not in range(128)
Logged from file Logs.py, line 167
Traceback (most recent call last):
  File "/home/chomwitt/Λήψεις/glmark2-master/waflib/Logs.py", line 85, in emit
    self.emit_override(record)
  File "/home/chomwitt/Λήψεις/glmark2-master/waflib/Logs.py", line 95, in emit_override
    msg=self.formatter.format(record)
  File "/home/chomwitt/Λήψεις/glmark2-master/waflib/Logs.py", line 135, in format
    return msg%rec.args
UnicodeDecodeError: 'ascii' codec can't decode byte 0xce in position 15: ordinal not in range(128)
Logged from file Logs.py, line 167
Traceback (most recent call last):
  File "/home/chomwitt/Λήψεις/glmark2-master/waflib/Scripting.py", line 120, in waf_entry_point
    run_commands()
  File "/home/chomwitt/Λήψεις/glmark2-master/waflib/Scripting.py", line 181, in run_commands
    ctx=run_command(cmd_name)
  File "/home/chomwitt/Λήψεις/glmark2-master/waflib/Scripting.py", line 172, in run_command
    ctx.execute()
  File "/home/chomwitt/Λήψεις/glmark2-master/waflib/Scripting.py", line 362, in execute
    return execute_method(self)
  File "/home/chomwitt/Λήψεις/glmark2-master/waflib/Build.py", line 99, in execute
    self.execute_build()
  File "/home/chomwitt/Λήψεις/glmark2-master/waflib/Build.py", line 106, in execute_build
    self.compile()
  File "/home/chomwitt/Λήψεις/glmark2-master/waflib/Build.py", line 173, in compile
    self.producer.start()
  File "/home/chomwitt/Λήψεις/glmark2-master/waflib/Runner.py", line 160, in start
    st=self.task_status(tsk)
  File "/home/chomwitt/Λήψεις/glmark2-master/waflib/Runner.py", line 143, in task_status
    self.error_handler(tsk)
  File "/home/chomwitt/Λήψεις/glmark2-master/waflib/Runner.py", line 120, in error_handler
    del self.bld.imp_sigs[tsk.uid()]
  File "/home/chomwitt/Λήψεις/glmark2-master/waflib/Build.py", line 489, in uid
    return Utils.h_list(lst)
  File "/home/chomwitt/Λήψεις/glmark2-master/waflib/Utils.py", line 349, in h_list
    return md5(repr(lst).encode()).digest()
UnicodeDecodeError: 'ascii' codec can't decode byte 0xce in position 16: ordinal not in range(128)

**Comment by aprekates** [comment]
Thanks .
I moved the source to another folder with no nonenglish components and its ok now.
