### ISSUE TITLE
waf script is not compatible with Python 3

### ISSUE THREAD

**Issue by marv** [glmark2/glmark2#120]
With Python 3.7 the `waf` invocation fails with:
```
env PKGCONFIG=armv6-unknown-linux-gnueabihf-pkg-config ./waf --verbose --jobs=1 configure --prefix=/usr/armv6-unknown-linux-gnueabihf/ --bindir=/usr/armv6-unknown-linux-gnueabihf/bin/ --sbindir=/usr/armv6-unknown-linux-gnueabihf/bin/ --libdir=/usr/armv6-unknown-linux-gnueabihf/lib/ --datadir=/usr/share/ --htmldir=/usr/share/doc/glmark2-scm/html/ --with-flavors=drm-gl,drm-glesv2,wayland-gl,wayland-glesv2
Waf: The wscript in '/var/tmp/paludis/build/gfx-glmark2-scm/work/glmark2-scm' is unreadable
Traceback (most recent call last):
  File "/var/tmp/paludis/build/gfx-glmark2-scm/work/glmark2-scm/waflib/Scripting.py", line 104, in waf_entry_point
    set_main_module(os.path.normpath(os.path.join(Context.run_dir,Context.WSCRIPT_FILE)))
  File "/var/tmp/paludis/build/gfx-glmark2-scm/work/glmark2-scm/waflib/Scripting.py", line 135, in set_main_module
    Context.g_module=Context.load_module(file_path)
  File "/var/tmp/paludis/build/gfx-glmark2-scm/work/glmark2-scm/waflib/Context.py", line 349, in load_module
    exec(compile(code,path,'exec'),module.__dict__)
  File "/var/tmp/paludis/build/gfx-glmark2-scm/work/glmark2-scm/wscript", line 23, in <module>
    FLAVORS_STR = ", ".join(sorted(FLAVORS.keys() + ['all-linux', 'all-win32']))
TypeError: unsupported operand type(s) for +: 'dict_keys' and 'list'
```

I'm not really familar with waf, but maybe just updating the waf script to a newer version would fix this?

**Comment by marv** [comment]
Taking a closer look at this, it's a regression introduced in 60f5e5a - see #121 for a fix

**Comment by afrantzis** [comment]
Fixed in https://github.com/glmark2/glmark2/commit/06e4728ba7312efa0fd595e30745e60ce88f1a4f . Thanks!
