### ISSUE TITLE
glmark2 and glmark2-es2 fail with SIGABRT

### ISSUE THREAD

**Issue by rathann** [glmark2/glmark2#126]
I'm getting this error most of the time, but sometimes, very rarely, it works. Any idea what's going on here?

It's version 2020.04 with the following patches applied:
06e4728
c50755b
ca6e787

Full backtrace from gdb:
```
$ gdb glmark2
GNU gdb (GDB) Fedora 9.1-5.fc32
...
Reading symbols from glmark2...
Reading symbols from /usr/lib/debug/usr/bin/glmark2-2020.04-2.fc32.x86_64.debug...
(gdb) run
Starting program: /usr/bin/glmark2 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
[New Thread 0x7ffff0ff0700 (LWP 48290)]
[New Thread 0x7fffeb7fa700 (LWP 48291)]
[New Thread 0x7fffeaff9700 (LWP 48292)]
[New Thread 0x7fffea7f8700 (LWP 48293)]
[New Thread 0x7fffe9ff7700 (LWP 48294)]
[New Thread 0x7fffe97f6700 (LWP 48295)]
[New Thread 0x7fffe8ff5700 (LWP 48296)]
[New Thread 0x7fffd3fff700 (LWP 48297)]
[New Thread 0x7fffd37fe700 (LWP 48298)]
[New Thread 0x7fffd2ffd700 (LWP 48299)]
[New Thread 0x7fffd27fc700 (LWP 48300)]
=======================================================
    glmark2 2020.04
=======================================================
    OpenGL Information
    GL_VENDOR:     X.Org
    GL_RENDERER:   AMD TAHITI (DRM 2.50.0, 5.7.8-200.fc32.x86_64, LLVM 10.0.0)
    GL_VERSION:    4.5 (Compatibility Profile) Mesa 20.1.2
=======================================================
terminate called after throwing an instance of '__gnu_cxx::recursive_init_error'
  what():  std::exception
[New Thread 0x7fffd1ffb700 (LWP 48301)]

Thread 8 "glmark2:sh1" received signal SIGABRT, Aborted.
[Switching to Thread 0x7fffe8ff5700 (LWP 48296)]
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50	  return ret;
(gdb) thread apply all where

Thread 13 (Thread 0x7fffd1ffb700 (LWP 48301)):
#0  clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:78
#1  0x00007ffff769c350 in annobin_start_thread.start () at pthread_create.c:362
#2  0x00007fffd1ffb700 in ?? ()
#3  0x0000000000000000 in ?? ()

Thread 12 (Thread 0x7fffd27fc700 (LWP 48300)):
#0  futex_wait_cancelable (private=0, expected=0, futex_word=0x72f730) at ../sysdeps/nptl/futex-internal.h:183
#1  __pthread_cond_wait_common (abstime=0x0, clockid=0, mutex=0x72f6e0, cond=0x72f708) at pthread_cond_wait.c:508
#2  __pthread_cond_wait (cond=0x72f708, mutex=0x72f6e0) at pthread_cond_wait.c:638
#3  0x00007ffff62bd2ab in cnd_wait (mtx=0x72f6e0, cond=0x72f708) at ../include/c11/threads_posix.h:155
#4  util_queue_thread_func (input=input@entry=0x67d940) at ../src/util/u_queue.c:275
#5  0x00007ffff62bcd7b in impl_thrd_routine (p=<optimized out>) at ../include/c11/threads_posix.h:87
#6  0x00007ffff769c432 in start_thread (arg=<optimized out>) at pthread_create.c:477
#7  0x00007ffff79919d3 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 11 (Thread 0x7fffd2ffd700 (LWP 48299)):
#0  futex_wait_cancelable (private=0, expected=0, futex_word=0x5e86f8) at ../sysdeps/nptl/futex-internal.h:183
#1  __pthread_cond_wait_common (abstime=0x0, clockid=0, mutex=0x5e86a8, cond=0x5e86d0) at pthread_cond_wait.c:508
#2  __pthread_cond_wait (cond=0x5e86d0, mutex=0x5e86a8) at pthread_cond_wait.c:638
#3  0x00007ffff62bd2ab in cnd_wait (mtx=0x5e86a8, cond=0x5e86d0) at ../include/c11/threads_posix.h:155
#4  util_queue_thread_func (input=input@entry=0x5e91c0) at ../src/util/u_queue.c:275
#5  0x00007ffff62bcd7b in impl_thrd_routine (p=<optimized out>) at ../include/c11/threads_posix.h:87
#6  0x00007ffff769c432 in start_thread (arg=<optimized out>) at pthread_create.c:477
#7  0x00007ffff79919d3 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 10 (Thread 0x7fffd37fe700 (LWP 48298)):
#0  futex_wait_cancelable (private=0, expected=0, futex_word=0x5e86f8) at ../sysdeps/nptl/futex-internal.h:183
#1  __pthread_cond_wait_common (abstime=0x0, clockid=0, mutex=0x5e86a8, cond=0x5e86d0) at pthread_cond_wait.c:508
#2  __pthread_cond_wait (cond=0x5e86d0, mutex=0x5e86a8) at pthread_cond_wait.c:638
#3  0x00007ffff62bd2ab in cnd_wait (mtx=0x5e86a8, cond=0x5e86d0) at ../include/c11/threads_posix.h:155
#4  util_queue_thread_func (input=input@entry=0x5e9180) at ../src/util/u_queue.c:275
#5  0x00007ffff62bcd7b in impl_thrd_routine (p=<optimized out>) at ../include/c11/threads_posix.h:87
#6  0x00007ffff769c432 in start_thread (arg=<optimized out>) at pthread_create.c:477
#7  0x00007ffff79919d3 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 9 (Thread 0x7fffd3fff700 (LWP 48297)):
#0  futex_wait_cancelable (private=0, expected=0, futex_word=0x5e7ff0) at ../sysdeps/nptl/futex-internal.h:183
#1  __pthread_cond_wait_common (abstime=0x0, clockid=0, mutex=0x5e7fa0, cond=0x5e7fc8) at pthread_cond_wait.c:508
#2  __pthread_cond_wait (cond=0x5e7fc8, mutex=0x5e7fa0) at pthread_cond_wait.c:638
#3  0x00007ffff62bd2ab in cnd_wait (mtx=0x5e7fa0, cond=0x5e7fc8) at ../include/c11/threads_posix.h:155
#4  util_queue_thread_func (input=input@entry=0x5e9120) at ../src/util/u_queue.c:275
#5  0x00007ffff62bcd7b in impl_thrd_routine (p=<optimized out>) at ../include/c11/threads_posix.h:87
#6  0x00007ffff769c432 in start_thread (arg=<optimized out>) at pthread_create.c:477
#7  0x00007ffff79919d3 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 8 (Thread 0x7fffe8ff5700 (LWP 48296)):
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff78b5895 in __GI_abort () at abort.c:79
#2  0x00007ffff7c5b961 in __gnu_cxx::__verbose_terminate_handler () at ../../../../libstdc++-v3/libsupc++/vterminate.cc:95
#3  0x00007ffff7c6742c in __cxxabiv1::__terminate (handler=<optimized out>) at ../../../../libstdc++-v3/libsupc++/eh_terminate.cc:48
#4  0x00007ffff7c67497 in std::terminate () at ../../../../libstdc++-v3/libsupc++/eh_terminate.cc:58
#5  0x00007ffff7c67749 in __cxxabiv1::__cxa_throw (obj=obj@entry=0x7fffcc0017a0, tinfo=0x7ffff7d9eae0 <typeinfo for __gnu_cxx::recursive_init_error>, dest=0x7ffff7c67a10 <__gnu_cxx::recursive_init_error::~recursive_init_error()>) at ../../../../libstdc++-v3/libsupc++/eh_throw.cc:95
#6  0x00007ffff7c5b544 in __cxxabiv1::throw_recursive_init_exception () at ../../../../libstdc++-v3/libsupc++/guard.cc:236
#7  __cxxabiv1::acquire (g=0x7ffff5da8268 <guard variable for llvm::hashing::detail::get_execution_seed()::seed>) at ../../../../libstdc++-v3/libsupc++/guard.cc:236
#8  __cxxabiv1::__cxa_guard_acquire (g=g@entry=0x7ffff5da8268 <guard variable for llvm::hashing::detail::get_execution_seed()::seed>) at ../../../../libstdc++-v3/libsupc++/guard.cc:345
#9  0x00007ffff1a4c0b8 in llvm::hashing::detail::get_execution_seed () at ../include/llvm/ADT/Hashing.h:186
#10 llvm::hashing::detail::hash_combine_range_impl<unsigned int const> (first=0x7fffe8ff4a40, last=0x7fffe8ff4a64) at ../include/llvm/ADT/Hashing.h:447
#11 0x00007ffff1a4c35b in llvm::hash_combine_range<unsigned int const*> (last=<optimized out>, first=<optimized out>) at ../include/llvm/ADT/Hashing.h:478
#12 llvm::FoldingSetNodeIDRef::ComputeHash (this=this@entry=0x7fffe8ff48d0) at ../lib/Support/FoldingSet.cpp:30
#13 0x00007ffff1a4c38d in llvm::FoldingSetNodeID::ComputeHash (this=this@entry=0x7fffe8ff4a30) at ../include/llvm/ADT/FoldingSet.h:283
#14 0x00007ffff1a4c3ee in llvm::FoldingSetBase::FindNodeOrInsertPos (this=this@entry=0x7fffcc001dc8, ID=..., InsertPos=@0x7fffe8ff4a28: 0x0) at ../lib/Support/FoldingSet.cpp:323
#15 0x00007ffff1beb054 in llvm::FoldingSetImpl<llvm::PMTopLevelManager::AUFoldingSetNode>::FindNodeOrInsertPos (InsertPos=@0x7fffe8ff4a28: 0x0, ID=..., this=0x7fffcc001dc8) at ../include/llvm/ADT/FoldingSet.h:444
#16 llvm::PMTopLevelManager::findAnalysisUsage (this=0x7fffcc001bc0, P=0x7fffcc002270) at ../lib/IR/LegacyPassManager.cpp:632
#17 0x00007ffff1bf07be in llvm::PMTopLevelManager::schedulePass (this=0x7fffcc001bc0, P=0x7fffcc002270) at ../lib/IR/LegacyPassManager.cpp:668
#18 0x00007ffff66e3da3 in ac_create_passmgr (check_ir=false, target_library_info=0x7fffcc001950) at ../src/amd/llvm/ac_llvm_util.c:209
#19 ac_init_llvm_compiler (compiler=compiler@entry=0x5e80b0, family=<optimized out>, tm_options=tm_options@entry=AC_TM_FORCE_DISABLE_XNACK) at ../src/amd/llvm/ac_llvm_util.c:373
#20 0x00007ffff6648d89 in si_init_compiler (sscreen=sscreen@entry=0x5e78a0, compiler=compiler@entry=0x5e80b0) at ../src/gallium/drivers/radeonsi/si_pipe.c:150
#21 0x00007ffff66787db in si_init_shader_selector_async (job=job@entry=0x7e2670, thread_index=thread_index@entry=1) at ../src/gallium/drivers/radeonsi/si_state_shaders.c:2384
#22 0x00007ffff62bd365 in util_queue_thread_func (input=input@entry=0x5e8f40) at ../src/util/u_queue.c:294
#23 0x00007ffff62bcd7b in impl_thrd_routine (p=<optimized out>) at ../include/c11/threads_posix.h:87
#24 0x00007ffff769c432 in start_thread (arg=<optimized out>) at pthread_create.c:477
#25 0x00007ffff79919d3 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 7 (Thread 0x7fffe97f6700 (LWP 48295)):
#0  0x00007ffff7918e04 in _int_free (av=0x7fffd8000020, p=<optimized out>, have_lock=<optimized out>) at malloc.c:4286
#1  0x00007ffff1f6cf8f in __gnu_cxx::new_allocator<char>::deallocate (__t=<optimized out>, __p=<optimized out>, this=0x7fffe97f5b50) at /usr/include/c++/10/ext/new_allocator.h:120
#2  std::allocator_traits<std::allocator<char> >::deallocate (__n=<optimized out>, __p=<optimized out>, __a=...) at /usr/include/c++/10/bits/alloc_traits.h:487
#3  std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_destroy (__size=<optimized out>, this=0x7fffe97f5b50) at /usr/include/c++/10/bits/basic_string.h:237
#4  std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_dispose (this=0x7fffe97f5b50) at /usr/include/c++/10/bits/basic_string.h:232
#5  std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string (this=0x7fffe97f5b50, __in_chrg=<optimized out>) at /usr/include/c++/10/bits/basic_string.h:658
#6  llvm::TargetPassConfig::addPass (this=this@entry=0x7fffd8011880, P=<optimized out>, verifyAfter=verifyAfter@entry=true, printAfter=printAfter@entry=true) at ../lib/CodeGen/TargetPassConfig.cpp:533
#7  0x00007ffff1f6d3e7 in llvm::TargetPassConfig::addPass (this=0x7fffd8011880, PassID=<optimized out>, verifyAfter=<optimized out>, printAfter=<optimized out>) at ../lib/CodeGen/TargetPassConfig.cpp:584
#8  0x00007ffff1f6e4f7 in llvm::TargetPassConfig::addMachinePasses (this=0x7fffd8011880) at ../lib/CodeGen/TargetPassConfig.cpp:927
#9  0x00007ffff1d69d70 in addPassesToGenerateCode (TM=..., PM=..., DisableVerify=DisableVerify@entry=true, MMIWP=...) at ../lib/CodeGen/LLVMTargetMachine.cpp:111
#10 0x00007ffff1d6cf75 in llvm::LLVMTargetMachine::addPassesToEmitFile (this=0x7fffd8004b50, PM=..., Out=..., DwoOut=0x0, FileType=llvm::CGFT_ObjectFile, DisableVerify=<optimized out>, MMIWP=0x7fffd8012610) at ../lib/CodeGen/LLVMTargetMachine.cpp:197
#11 0x00007ffff66e3157 in ac_create_llvm_passes (tm=0x7fffd8004b50) at ../src/amd/llvm/ac_llvm_helper.cpp:239
#12 0x00007ffff6648d92 in si_init_compiler (sscreen=sscreen@entry=0x5e78a0, compiler=compiler@entry=0x5e8070) at ../src/gallium/drivers/radeonsi/si_pipe.c:151
#13 0x00007ffff66787db in si_init_shader_selector_async (job=job@entry=0x7d3020, thread_index=thread_index@entry=0) at ../src/gallium/drivers/radeonsi/si_state_shaders.c:2384
#14 0x00007ffff62bd365 in util_queue_thread_func (input=input@entry=0x5ea110) at ../src/util/u_queue.c:294
#15 0x00007ffff62bcd7b in impl_thrd_routine (p=<optimized out>) at ../include/c11/threads_posix.h:87
#16 0x00007ffff769c432 in start_thread (arg=<optimized out>) at pthread_create.c:477
#17 0x00007ffff79919d3 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 6 (Thread 0x7fffe9ff7700 (LWP 48294)):
#0  futex_wait_cancelable (private=0, expected=0, futex_word=0x5e8cb8) at ../sysdeps/nptl/futex-internal.h:183
#1  __pthread_cond_wait_common (abstime=0x0, clockid=0, mutex=0x5e8c68, cond=0x5e8c90) at pthread_cond_wait.c:508
#2  __pthread_cond_wait (cond=0x5e8c90, mutex=0x5e8c68) at pthread_cond_wait.c:638
#3  0x00007ffff62bd2ab in cnd_wait (mtx=0x5e8c68, cond=0x5e8c90) at ../include/c11/threads_posix.h:155
#4  util_queue_thread_func (input=input@entry=0x5ea8a0) at ../src/util/u_queue.c:275
#5  0x00007ffff62bcd7b in impl_thrd_routine (p=<optimized out>) at ../include/c11/threads_posix.h:87
#6  0x00007ffff769c432 in start_thread (arg=<optimized out>) at pthread_create.c:477
#7  0x00007ffff79919d3 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 5 (Thread 0x7fffea7f8700 (LWP 48293)):
#0  futex_wait_cancelable (private=0, expected=0, futex_word=0x5e8cb8) at ../sysdeps/nptl/futex-internal.h:183
#1  __pthread_cond_wait_common (abstime=0x0, clockid=0, mutex=0x5e8c68, cond=0x5e8c90) at pthread_cond_wait.c:508
#2  __pthread_cond_wait (cond=0x5e8c90, mutex=0x5e8c68) at pthread_cond_wait.c:638
#3  0x00007ffff62bd2ab in cnd_wait (mtx=0x5e8c68, cond=0x5e8c90) at ../include/c11/threads_posix.h:155
#4  util_queue_thread_func (input=input@entry=0x5ea0d0) at ../src/util/u_queue.c:275
#5  0x00007ffff62bcd7b in impl_thrd_routine (p=<optimized out>) at ../include/c11/threads_posix.h:87
#6  0x00007ffff769c432 in start_thread (arg=<optimized out>) at pthread_create.c:477
#7  0x00007ffff79919d3 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 4 (Thread 0x7fffeaff9700 (LWP 48292)):
#0  futex_wait_cancelable (private=0, expected=0, futex_word=0x5e8cb8) at ../sysdeps/nptl/futex-internal.h:183
#1  __pthread_cond_wait_common (abstime=0x0, clockid=0, mutex=0x5e8c68, cond=0x5e8c90) at pthread_cond_wait.c:508
#2  __pthread_cond_wait (cond=0x5e8c90, mutex=0x5e8c68) at pthread_cond_wait.c:638
#3  0x00007ffff62bd2ab in cnd_wait (mtx=0x5e8c68, cond=0x5e8c90) at ../include/c11/threads_posix.h:155
#4  util_queue_thread_func (input=input@entry=0x5e9ef0) at ../src/util/u_queue.c:275
#5  0x00007ffff62bcd7b in impl_thrd_routine (p=<optimized out>) at ../include/c11/threads_posix.h:87
#6  0x00007ffff769c432 in start_thread (arg=<optimized out>) at pthread_create.c:477
#7  0x00007ffff79919d3 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 3 (Thread 0x7fffeb7fa700 (LWP 48291)):
#0  futex_wait_cancelable (private=0, expected=0, futex_word=0x5e8cb8) at ../sysdeps/nptl/futex-internal.h:183
#1  __pthread_cond_wait_common (abstime=0x0, clockid=0, mutex=0x5e8c68, cond=0x5e8c90) at pthread_cond_wait.c:508
#2  __pthread_cond_wait (cond=0x5e8c90, mutex=0x5e8c68) at pthread_cond_wait.c:638
#3  0x00007ffff62bd2ab in cnd_wait (mtx=0x5e8c68, cond=0x5e8c90) at ../include/c11/threads_posix.h:155
#4  util_queue_thread_func (input=input@entry=0x5e9820) at ../src/util/u_queue.c:275
#5  0x00007ffff62bcd7b in impl_thrd_routine (p=<optimized out>) at ../include/c11/threads_posix.h:87
#6  0x00007ffff769c432 in start_thread (arg=<optimized out>) at pthread_create.c:477
#7  0x00007ffff79919d3 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 2 (Thread 0x7ffff0ff0700 (LWP 48290)):
#0  futex_wait_cancelable (private=0, expected=0, futex_word=0x5e6d1c) at ../sysdeps/nptl/futex-internal.h:183
#1  __pthread_cond_wait_common (abstime=0x0, clockid=0, mutex=0x5e6cc8, cond=0x5e6cf0) at pthread_cond_wait.c:508
#2  __pthread_cond_wait (cond=0x5e6cf0, mutex=0x5e6cc8) at pthread_cond_wait.c:638
#3  0x00007ffff62bd2ab in cnd_wait (mtx=0x5e6cc8, cond=0x5e6cf0) at ../include/c11/threads_posix.h:155
#4  util_queue_thread_func (input=input@entry=0x5e72c0) at ../src/util/u_queue.c:275
#5  0x00007ffff62bcd7b in impl_thrd_routine (p=<optimized out>) at ../include/c11/threads_posix.h:87
#6  0x00007ffff769c432 in start_thread (arg=<optimized out>) at pthread_create.c:477
#7  0x00007ffff79919d3 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 1 (Thread 0x7ffff783f740 (LWP 48286)):
#0  clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:78
#1  0x00007ffff769b2fc in create_thread (pd=pd@entry=0x7fffd1ffb700, attr=attr@entry=0x7fffffffd2b0, stopped_start=stopped_start@entry=0x7fffffffd2ae, stackaddr=stackaddr@entry=0x7fffd1ffafc0, thread_ran=thread_ran@entry=0x7fffffffd2af) at ../sysdeps/unix/sysv/linux/createthread.c:101
#2  0x00007ffff769cc2d in __pthread_create_2_1 (newthread=newthread@entry=0x7fffffffd338, attr=attr@entry=0x0, start_routine=start_routine@entry=0x7ffff62bcd60 <impl_thrd_routine>, arg=arg@entry=0x5a2cf0) at pthread_create.c:817
#3  0x00007ffff62bcfe7 in thrd_create (func=0x7ffff62bd230 <util_queue_thread_func>, arg=0x7d3b40, thr=0x7fffffffd338) at ../include/c11/threads_posix.h:289
#4  u_thread_create (param=param@entry=0x7d3b40, routine=0x7ffff62bd230 <util_queue_thread_func>) at ../src/util/u_thread.h:61
#5  0x00007ffff62bd085 in util_queue_create_thread (queue=queue@entry=0x865f38, index=index@entry=0) at ../src/util/u_queue.c:326
#6  0x00007ffff62bd7e1 in util_queue_init (queue=queue@entry=0x865f38, name=name@entry=0x7ffff6dd8e0b "gdrv", max_jobs=max_jobs@entry=8, num_threads=num_threads@entry=1, flags=flags@entry=0) at ../src/util/u_queue.c:442
#7  0x00007ffff68c494b in threaded_context_create (pipe=pipe@entry=0x7e2f00, parent_transfer_pool=parent_transfer_pool@entry=0x5e7dc8, replace_buffer=0x7ffff669c2d0 <si_replace_buffer_storage>, create_fence=0x0, out=0x7e3350) at ../src/gallium/auxiliary/util/u_threaded_context.c:2656
#8  0x00007ffff6647d33 in si_pipe_create_context (screen=0x5e78a0, priv=<optimized out>, flags=<optimized out>) at ../src/gallium/drivers/radeonsi/si_pipe.c:710
#9  0x00007ffff5f3a840 in st_api_create_context (stapi=<optimized out>, smapi=0x5e3e30, attribs=0x7fffffffd6d0, error=0x7fffffffd6cc, shared_stctxi=0x0) at ../src/mesa/state_tracker/st_manager.c:928
#10 0x00007ffff5f2ef52 in dri_create_context (api=<optimized out>, visual=0x68a820, cPriv=0x7d04a0, ctx_config=<optimized out>, error=0x7fffffffd8dc, sharedContextPrivate=<optimized out>) at ../src/gallium/state_trackers/dri/dri_context.c:163
#11 0x00007ffff63cf7cb in driCreateContextAttribs (screen=0x5e25d0, api=<optimized out>, config=0x68a820, shared=<optimized out>, num_attribs=<optimized out>, attribs=<optimized out>, error=0x7fffffffd8dc, data=0x7d22b0) at ../src/mesa/drivers/dri/common/dri_util.c:475
#12 0x00007ffff7663df3 in dri3_create_context_attribs (base=0x540080, config_base=<optimized out>, shareList=<optimized out>, num_attribs=num_attribs@entry=1, attribs=attribs@entry=0x7fffffffd8e0, error=error@entry=0x7fffffffd8dc) at ../src/glx/dri3_glx.c:315
#13 0x00007ffff7663ed8 in dri3_create_context (base=<optimized out>, config_base=<optimized out>, shareList=<optimized out>, renderType=<optimized out>) at ../src/glx/dri3_glx.c:347
#14 0x00007ffff764f158 in CreateContext (dpy=dpy@entry=0x51d0a0, generic_id=361, config=config@entry=0x6a7ae0, shareList_user=shareList_user@entry=0x0, allowDirect=allowDirect@entry=1, code=code@entry=24, renderType=32788, screen=0) at ../src/glx/glxcmds.c:343
#15 0x00007ffff764f489 in glXCreateNewContext (dpy=0x51d0a0, fbconfig=0x6a7ae0, renderType=32788, shareList=0x0, allowDirect=1) at ../src/glx/glxcmds.c:1642
#16 0x00007ffff7789e48 in glXCreateNewContext (dpy=0x51d0a0, config=0x6a7ae0, render_type=32788, share_list=0x0, direct=1) at libglx.c:265
#17 0x0000000000412f78 in GLStateGLX::ensure_glx_context (this=0x7fffffffdb80) at ../src/gl-state-glx.cpp:278
#18 GLStateGLX::ensure_glx_context (this=0x7fffffffdb80) at ../src/gl-state-glx.cpp:270
#19 0x0000000000412fd0 in GLStateGLX::valid (this=0x7fffffffdb80) at ../src/gl-state-glx.cpp:70
#20 0x0000000000411282 in CanvasGeneric::do_make_current (this=this@entry=0x7fffffffdbd0) at ../src/canvas-generic.cpp:279
#21 0x0000000000411788 in CanvasGeneric::reset (this=0x7fffffffdbd0) at ../src/canvas-generic.cpp:59
#22 0x000000000041d99a in MainLoop::step (this=this@entry=0x7d16f0) at ../src/main-loop.cpp:117
#23 0x000000000040ff70 in do_benchmark (canvas=...) at ../src/main.cpp:123
#24 0x000000000040e1be in main (argc=<optimized out>, argv=<optimized out>) at ../src/main.cpp:221
(gdb) 
```

**Comment by lucmann** [comment]
I'm not sure if [this](https://gitlab.freedesktop.org/mesa/mesa/-/issues/3199) is the same with yours.

**Comment by rathann** [comment]
This is no longer reproducible with latest releases of glmark2 and gcc on Fedora 34. I guess this can be closed.

**Comment by afrantzis** [comment]
Thanks!
