### ISSUE TITLE
Build using waf failes due to removal of `imp` package, with Python 3.12

### ISSUE THREAD

**Issue by kakakaya** [glmark2/glmark2#234]
Hello! Thank you for maintaining nice project!

I'm trying to use the glmark2 on my system, which has Python 3.12, but it fails while installing. The error message says like this:

```
Traceback (most recent call last):
  File "/home/kakakaya/.phoronix-test-suite/installed-tests/pts/glmark2-1.4.0/glmark2-2023.01/./waf", line 163, in <module>
    from waflib import Scripting
  File "/home/kakakaya/.phoronix-test-suite/installed-tests/pts/glmark2-1.4.0/glmark2-2023.01/waflib/Scripting.py", line 6, in <module>
    from waflib import Utils,Configure,Logs,Options,ConfigSet,Context,Errors,Build,Node
  File "/home/kakakaya/.phoronix-test-suite/installed-tests/pts/glmark2-1.4.0/glmark2-2023.01/waflib/Configure.py", line 6, in <module>
    from waflib import ConfigSet,Utils,Options,Logs,Context,Build,Errors
  File "/home/kakakaya/.phoronix-test-suite/installed-tests/pts/glmark2-1.4.0/glmark2-2023.01/waflib/Options.py", line 6, in <module>
    from waflib import Logs,Utils,Context,Errors
  File "/home/kakakaya/.phoronix-test-suite/installed-tests/pts/glmark2-1.4.0/glmark2-2023.01/waflib/Context.py", line 5, in <module>
    import os,re,imp,sys
ModuleNotFoundError: No module named 'imp'
```

According to Python 3.11 document, the `imp` package is removed in Python 3.12.

> Deprecated since version 3.4, will be removed in version 3.12: The [imp](https://docs.python.org/3.11/library/imp.html#module-imp) module is deprecated in favor of [importlib](https://docs.python.org/3.11/library/importlib.html#module-importlib).
[imp — Access the import internals — Python 3.11.8 documentation](https://docs.python.org/3.11/library/imp.html)

Therefore, I suggest the following:
- Specify the supported Python version as <3.12
- Alternatively, update the project to support Python 3.12

Best regards.

----
I've redirected from this issue: 
- https://github.com/phoronix-test-suite/phoronix-test-suite/issues/801

**Comment by afrantzis** [comment]
Thanks for the report, but waf support was recently completely removed from the project (20dcaf368c3e8d01f99d60327600a6048122ae0a). Please use meson to build glmark2.
